#!/usr/bin/env python3
"""Write ASSUMPTIONS.md: every result this development assumes, with its statement.

A reader who is told that something is assumed should be able to see exactly
what.  This lists each node whose state is `FROZEN`, with where the paper cites
it and the verbatim Lean proposition that is assumed.

    python3 tools/assumptions.py            # write ASSUMPTIONS.md
    python3 tools/assumptions.py --check    # fail if the file on disk is stale
"""
import pathlib, re, sys

try:
    import yaml
except ImportError:
    sys.exit("assumptions.py: PyYAML is required")

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN, END = "-- FROZEN-STATEMENT-BEGIN", "-- FROZEN-STATEMENT-END"


def frozen_block(path):
    t = (ROOT / path).read_text(encoding="utf-8")
    return t[t.index(BEGIN) + len(BEGIN):t.index(END)].strip("\n")


def companions(nodes):
    """Assumed propositions for which this repository also supplies a proof.

    The proof lives beside the proposition in a `*Proved.lean` companion; some
    prove it outright and some under hypotheses the paper's setting satisfies.
    """
    out = {}
    for n in nodes:
        if n.get("state") in ("SEALED", "PROVED") and n["file"].endswith("Proved.lean"):
            out[pathlib.Path(n["file"]).name[: -len("Proved.lean")]] = n
    return out


def render():
    man = yaml.safe_load((ROOT / "ledger" / "manifest.yaml").read_text(encoding="utf-8"))
    assumed = [n for n in man["nodes"] if n.get("state") == "FROZEN"]
    comp = companions(man["nodes"])
    out = ["# What this development assumes", ""]
    if not assumed:
        out += ["Nothing.  Every registered statement in this repository is proved here,",
                "from Mathlib and the libraries named in the README; no result is carried",
                "as an assumed hypothesis.", ""]
        return "\n".join(out)
    out += [
        "The results below are quoted by the paper from the literature and are **not",
        "proved here**.  Each is a proposition carried as an explicit hypothesis by",
        "every theorem whose proof uses it, so a theorem's statement shows exactly",
        "which of these it rests on.",
        "",
        f"There are {len(assumed)} of them.  Each entry gives the node id, where the paper",
        "cites the result, and the verbatim Lean proposition that is assumed.",
        "",
        "This file is generated by `python3 tools/assumptions.py` from",
        "`ledger/manifest.yaml` and the Lean sources; do not edit it by hand.",
        "",
    ]
    withproof = [n for n in assumed if pathlib.Path(n["file"]).stem in comp]
    if withproof:
        out += [f"Of these, **{len(withproof)} are also proved in this repository** and so need not "
                "be taken on trust; each is marked below with the companion that proves it. "
                f"The remaining **{len(assumed) - len(withproof)}** are assumed outright.", ""]
    for n in sorted(assumed, key=lambda x: x["id"]):
        c = comp.get(pathlib.Path(n["file"]).stem)
        out += [f"## `{n['id']}`", "",
                f"* **Lean name** `{n['export']}`",
                f"* **File** `{n['file']}`",
                f"* **Cited at** {n['source']}",
                (f"* **Also proved here** by `{c['id']}` in `{c['file']}`, so this hypothesis "
                 "can be discharged rather than assumed" if c else
                 "* **Not proved here**: this one is assumed outright"),
                "",
                "```lean",
                frozen_block(n["file"]),
                "```",
                ""]
    return "\n".join(out)


text = render()
target = ROOT / "ASSUMPTIONS.md"
if "--check" in sys.argv[1:]:
    cur = target.read_text(encoding="utf-8") if target.exists() else ""
    if cur != text:
        sys.exit("assumptions: ASSUMPTIONS.md is stale; rerun tools/assumptions.py")
    print("assumptions: OK (ASSUMPTIONS.md is current)")
else:
    target.write_text(text, encoding="utf-8")
    n = text.count("\n## `")
    print(f"assumptions: wrote ASSUMPTIONS.md ({n} assumed result(s))")
