"""Regenerate the manifest-derived tables in README.md and CORRESPONDENCE.md.

Both documents restate what `ledger/manifest.yaml` already records: how many
nodes exist, what state each is in, and where in the paper each one comes from.
Restated facts go stale.  Everything between a BEGIN/END marker pair below is
generated from the manifest, so the prose in those files never disagrees with
the checker again.

    python3 tools/sync_docs.py            # check, exit 1 if a block is stale
    python3 tools/sync_docs.py --write    # regenerate the blocks in place
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("sync_docs.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"

SURFACE_BEGIN = "<!-- FROZEN-SURFACE-BEGIN (generated by tools/sync_docs.py) -->"
SURFACE_END = "<!-- FROZEN-SURFACE-END -->"
STATUS_BEGIN = "<!-- STATUS-BEGIN (generated by tools/sync_docs.py) -->"
STATUS_END = "<!-- STATUS-END -->"
SQUARE_BEGIN = "<!-- SQUARE-PERTURBATIONS-BEGIN (generated by tools/sync_docs.py) -->"
SQUARE_END = "<!-- SQUARE-PERTURBATIONS-END -->"


def square_perturbations_block(nodes: list[dict]) -> str:
    """The finite-index translation hypothesis and the square perturbation conclusions."""
    node = next(n for n in nodes if n["id"] == "prop-perturbations-square")
    source = (ROOT / node["file"]).read_text(encoding="utf-8")
    statement = source.split("-- FROZEN-STATEMENT-BEGIN", 1)[1].split(
        "-- FROZEN-STATEMENT-END", 1)[0]
    required = (
        "∀ (Λ : AddSubgroup Site) [Λ.FiniteIndex]",
        "∀ z ∈ Λ, ∀ v, Measure.map (squarePeriodic.shiftNbr z) (ν v) = ν (v + z)",
    )
    if any(fragment not in statement for fragment in required):
        raise ValueError("square perturbation summary requires the finite-index lattice statement")
    return (
        "Proposition 1.2 on the square lattice gives one `δ > 0` for all independent\n"
        "rotor laws whose marginal at every vertex has total variation distance less\n"
        "than `δ` from uniform. The walk is almost surely recurrent from each start.\n"
        "For every finite-index translation sublattice `Λ ≤ ℤ²`, invariance of the\n"
        "marginal laws under `Λ` also gives a deterministic compact convex body `B`\n"
        "with the origin in its interior and positive constants `κ, c`. In coordinates\n"
        "centered at the starting vertex,\n"
        "`n^(-1) A_n → B`, `t^(-1/3) R_t → κ B`, and `|R_t| / t^(2/3) → c` almost surely.\n"
        "The radius is independent of `Λ`. The frozen statement also includes finite\n"
        "circuit times and the inner and outer lattice-point bounds.\n\n"
        f"See [`{node['export']}`]({node['file']}); its cited inputs are listed below.")

LABEL_RE = re.compile(r"label ([A-Za-z][A-Za-z0-9:_-]*)")
RANGE_RE = re.compile(r"rotor\.tex:\d+-\d+")


def paper_cell(source: str) -> str:
    """The `paper` column: line range plus label, or the guard's own wording."""
    rng = RANGE_RE.search(source)
    lab = LABEL_RE.search(source)
    if rng and lab:
        return f"`{rng.group(0)}`, `{lab.group(1)}`"
    return source


def surface_table(nodes: list[dict]) -> str:
    rows = ["| id | Lean | paper | state |", "|---|---|---|---|"]
    for n in nodes:
        rows.append(
            f"| `{n['id']}` | `{n['export']}` | {paper_cell(n['source'])} "
            f"| {n['state']} |")
    return "\n".join(rows)


def status_block(nodes: list[dict]) -> str:
    counts = Counter(n["state"] for n in nodes)
    parts = ", ".join(f"{counts[s]} `{s}`" for s in sorted(counts))
    draft = [n["id"] for n in nodes if n["state"] == "DRAFT_SORRY"]
    # State what is actually true.  Claiming a clean axiom closure while a
    # `DRAFT_SORRY` node exists is exactly the drift these blocks exist to stop.
    if draft:
        which = ", ".join(f"`{i}`" for i in draft)
        body = (
            f"The {len(nodes) - len(draft)} sealed nodes are machine-checked and no\n"
            f"sealed node's axiom closure contains `sorryAx`.  Still open: {which},\n"
            f"whose statement is frozen and whose proof is a registered `sorry`.")
    else:
        body = (
            "Every node's proof is machine-checked and its axiom closure contains\n"
            "no `sorryAx`.")
    return (
        f"Status: **{len(nodes)} frozen nodes — {parts}.**  {body}  Run\n"
        f"`python3 tools/check_axioms.py` to confirm.  Counts here are generated\n"
        f"from `ledger/manifest.yaml` by `python3 tools/sync_docs.py`; do not\n"
        f"edit them by hand and do not trust a count in prose that the checkers\n"
        f"have not confirmed.")


def splice(text: str, begin: str, end: str, body: str) -> str:
    i, j = text.find(begin), text.find(end)
    if i < 0 or j < 0:
        raise LookupError(f"missing marker pair {begin!r}")
    return text[:i] + begin + "\n\n" + body + "\n\n" + text[j:]


def main() -> int:
    write = "--write" in sys.argv[1:]
    nodes = (yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}).get("nodes") or []

    square = square_perturbations_block(nodes)
    targets = [
        (ROOT / "README.md", SQUARE_BEGIN, SQUARE_END, square),
        (ROOT / "CORRESPONDENCE.md", SQUARE_BEGIN, SQUARE_END, square),
        (ROOT / "CORRESPONDENCE.md", SURFACE_BEGIN, SURFACE_END, surface_table(nodes)),
        (ROOT / "README.md", STATUS_BEGIN, STATUS_END, status_block(nodes)),
    ]

    originals = {path: path.read_text(encoding="utf-8") for path, _, _, _ in targets}
    generated = dict(originals)
    for path, begin, end, body in targets:
        text = generated[path]
        try:
            want = splice(text, begin, end, body)
        except LookupError as exc:
            print(f"sync_docs: {path.name}: {exc}", file=sys.stderr)
            return 2
        generated[path] = want

    stale = [(path, want) for path, want in generated.items() if want != originals[path]]
    if not stale:
        print(f"sync_docs: OK ({len(nodes)} nodes; README.md and "
              f"CORRESPONDENCE.md agree with the manifest)")
        return 0

    for path, want in stale:
        print(f"  stale: {path.relative_to(ROOT)}")
        if write:
            path.write_text(want, encoding="utf-8")

    if not write:
        print("\nsync_docs: rerun with --write to regenerate", file=sys.stderr)
        return 1
    print(f"\nsync_docs: regenerated {len(stale)} block(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
